### ISSUE TITLE
Any way to set an animation for when a page is FIRST loaded?

### ISSUE THREAD

**Issue by iDVB** [TylerBarnes/gatsby-plugin-transition-link#132]
Would be great if there was a way to set an animation for when a page is FIRST loaded versus a page transition between local pages.  Like giving the homepage two transitions:
FIRST LOAD vs PAGE TRANSITIONED TO.

Is there a way to do this?

**Comment by TylerBarnes** [comment]
Hey @iDVB , it's definitely do-able as things are now though the implementation details will vary based on your setup. 
In transition link, every animation depends on the props added to the link component. Since an initial load isn't related to a link, there isn't a way to add support for this. 
What you can do though is use either `componentDidMount()` or `useEffect({}, [])` to perform an animation when your page loads. If you want to share animations between transition link and a regular animation you'll need to do some work in writing a re-usable function for your animation that works in both contexts.

Closing this as outside the scope of this package but feel free to ask any more questions you may have here.

Thanks!

**Comment by TylerBarnes** [comment]
Also, in CDM or useEffect, you'll want to check if the page is transitioning before running your page load animation, so that it doesn't fire when transitioning.

**Comment by iDVB** [comment]
Thanks. I figured as much. Just curious how you might know the different
between first load and page transition.

D

**Comment by TylerBarnes** [comment]
@iDVB the transition status is available as props on the page. You should be able to use an if statement based on which transition status the page is in. The prop you're looking for would be "current" as that one gives you info about the current pages transition state.
