### ISSUE TITLE
AniLink Paint Drop seems very Jaggy & slow

### ISSUE THREAD

**Issue by joebentaylor1995** [TylerBarnes/gatsby-plugin-transition-link#148]
When using the paintdrop transition, it seems quite janky. see: [Colorworld](colorworld.netlify.com)

Is there a way to improve the performance of this?

**Comment by TylerBarnes** [comment]
@joebentaylor1995 there is currently a performance issue due to transition-link cloning each page and injecting transition status props into the page. It causes unnecessary re-rendering of the entire exiting and entering pages. 
I'm currently working on a V2 that will remove this functionality but as it's a breaking change I wont be able to add it as a patch or minor. Maybe in the meantime it could be a plugin option that disables this functionality? 
On my computer the performance of paintDrip is good in your site, but I know on computers with less power it can be an issue depending on the site.
PaintDrip itself is quite complicated as it needs to use canvas for performance reasons. See https://github.com/TylerBarnes/gatsby-plugin-transition-link/blob/master/src/AniLink/PaintDrip.js

Additionally, part of the paintDrip animation is the next page sliding in slightly. 

So two things could be done if you don't want to or don't have time to wait for V2
	- add a plugin option to disable injecting props into pages
	- add an anilink paintDrip option to disable sliding in the entering page

If you're interested in helping out I can direct you to how to make these changes for a PR or two!
Let me know :)

**Comment by TylerBarnes** [comment]
I love your site BTW. The animations between pages are awesome!

**Comment by TylerBarnes** [comment]
Ok so I just went ahead and added the option to not inject props. Try it out and let me know what you think.
`yarn add gatsby-plugin-transition-link@1.16.0`

```
 {
      resolve: 'gatsby-plugin-transition-link',
      options: {
        injectPageProps: false,
      },
    },
```

**Comment by TylerBarnes** [comment]
You can also try making your pages pureComponents in case they're still re-rendering https://reactjs.org/docs/react-api.html#reactpurecomponent. I saw just now that not injecting props reduced the number of renders but purecomponent could potentially reduce that even further

**Comment by TylerBarnes** [comment]
There was a bug in 1.16, use `yarn add gatsby-plugin-transition-link@1.16.1` instead

**Comment by joebentaylor1995** [comment]
Hey @TylerBarnes ive implemented your solution, but the jaggyness towards the end of the animation still remains, it does seem more performant, but the animation is still not quite right. you can check it out from the same link as before.

**Comment by joebentaylor1995** [comment]
Also @TylerBarnes it seems that i can see the previous page for ever so slightly of a second after the animation has finished

**Comment by joebentaylor1995** [comment]
> Hey @TylerBarnes ive implemented your solution, but the jaggyness towards the end of the animation still remains, it does seem more performant, but the animation is still not quite right. you can check it out from the same link as before.

After messing with a few things, io managed to get the animation looking pretty sweet and with a good transition, its just that previous page fade

**Comment by TylerBarnes** [comment]
@joebentaylor1995 I'm not seeing the previous page at the end. What OS and browser are you in? Also what are the specs on your machine? Maybe I can more closely replicate your set up. Or maybe a GIF would help?

**Comment by joebentaylor1995** [comment]
I could put you onto the repo to take a look if you want?
My computer doesnt want to seem to let me take a gif of the screen for some reason... Have you got something i can message you on directly to shwo you the issue? @TylerBarnes

**Comment by TylerBarnes** [comment]
@joebentaylor1995 I think we're in different timezones but we could do a zoom call (I'm in PST time). Unfortunately I will be going away on vacation from tomorrow (the 8th) until the 19th. Message me on twitter to get a call set up. If we can't get it worked out before then I would recommend using the paintDrip animation to create your own transition-link animation. You can copy this file https://github.com/TylerBarnes/gatsby-plugin-transition-link/blob/master/src/AniLink/PaintDrip.js and try tweaking it to suit your needs. If you go that route, let me know what fixed your issue or if you're up to it I'd love a PR fixing it.

**Comment by joebentaylor1995** [comment]
Are you available now?

**Comment by TylerBarnes** [comment]
Just dm'ed you a zoom link

**Comment by TylerBarnes** [comment]
@joebentaylor1995 I believe I've fixed this, please re-open if not.
So it looks like in paintDrip the exit timing was hardcoded instead of based on the duration of the animation. Try `gatsby-plugin-transition-link@1.16.2` for a fix!

**Comment by TylerBarnes** [comment]
Your menu timer of 600ms is good still

**Comment by joebentaylor1995** [comment]
@TylerBarnes Fixed!!! Absolute legend.

**Comment by TylerBarnes** [comment]
Glad to hear it!
I'd love to put colorworld in the list of sites that use transition-link when it's ready! It's a really nice site!

**Comment by Aziz-Rashid** [comment]
how can i use any transition in gatsby without navbar reload it
