### ISSUE TITLE
Persistent Layout Issues

### ISSUE THREAD

**Issue by bradleyDouglas** [TylerBarnes/gatsby-plugin-transition-link#158]
Hello

Thanks for the plugin, it really helps with link specific transitions! 

I've used the plugin with another project and didn't have any issues, but for some reason, I'm running into some serious issues on this project. 

The first issue I noticed is that my Layout Component is being mounted twice. I've gone through the pages and that component is not included in any page, so I can't figure out why it's doing this. 

The second issue I'm noticing is that the Layout Component is being mounted on every page refresh. I'm doing a simple console log on Mount and Unmount - via useEffect - and based on that you will see 'Layout Mounted' and 'Layout has unmounted' in the console. 

Here's a link to the staging site:
https://staging-obd.netlify.com/

I can also get you access to my code via a repository if needed. 

Thanks in advance!

Brad

**Comment by bradleyDouglas** [comment]
It appears that the layout component is being mounted/unmounted twice on the initial load. After that, it mounts and unmounts once per page load. This is what is causing my error as my Intro Component is being rendred twice and causing janky animations and an error in the console.

**Comment by TylerBarnes** [comment]
Hey @bradleyDouglas, apologies for the late response here! This seems odd. If you can share your code that would be super helpful. Off the top of my head I'm not sure what would be causing this. I've been planning on adding support for `gatsby-plugin-layout` instead of handling it internally. If I can use your repo, I might just make that work and see if it fixes the issue.

**Comment by bradleyDouglas** [comment]
@TylerBarnes, no worries. Here's a link to the repository

https://github.com/bozell-omaha/obd

I appreciate the help!

**Comment by TylerBarnes** [comment]
Ok, so there are a couple things happening here. First, your mounted/unmounted check isn't 100% accurate because it's running your effect on every render.

The second param in useEffect is when to re-run the effect.

```js
    useEffect(() => {
        console.log(`Layout Mounted`)

        return function unmounted() {
            console.log(`Layout has unmounted`)
        }
    })
```

Since you have no second param it will re-run over and over

If you change it to 
```js
    useEffect(() => {
        console.log(`Layout Mounted`)

        return function unmounted() {
            console.log(`Layout has unmounted`)
        }
    }, [])
```

it will only run when the component mounts.
So that's only half the issue because there's definitely a problem here.
I tried internally removing layouts and using gatsby-plugin-layout instead and it did fix things which is nice! However, the way I tested it is a breaking change, and I need to make it non-breaking but I'm out of time today. I'll have a look again tomorrow!

**Comment by bradleyDouglas** [comment]
AH, great catch. Definitely fixed that console log issue. Curious to see what you come up with on the other front. I can't seem to figure it out. 

Thanks!

**Comment by TylerBarnes** [comment]
Hey @bradleyDouglas , upgrade to `gatsby-plugin-transition-link@1.17.5` for a fix. I ended up needing to move a couple things around internally so that it wasn't remounting. You should be able to use the built in layout component or `gatsby-plugin-layout` no problem now (as long as TL comes before `gatsby-plugin-layout` in your config).
Let me know if that doesn't fix it for you and I can take another look!

**Comment by bradleyDouglas** [comment]
@TylerBarnes Just updated - was out on vacation - and everything seems to work great. Appreciate it!

**Comment by TylerBarnes** [comment]
Woo! Glad to hear it. Happy holidays @bradleyDouglas 
Let me know if you run into any other problems
