### ISSUE TITLE
Cannot read property 'disableAnimation' of undefined

### ISSUE THREAD

**Issue by tijsluitse** [TylerBarnes/gatsby-plugin-transition-link#161]
Hi there, 

I'm getting this error, any idea?

**Comment by TylerBarnes** [comment]
Hey @tijsluitse can you share a reproduction repo so I can have a look?
Thanks!

**Comment by VeFoWe** [comment]
I'm experiencing the exact same issue. After setting up a basic Gatsby instance and following the instructions here: https://www.gatsbyjs.org/docs/adding-page-transitions-with-plugin-transition-link/
(with the only difference of using Yarn instead of NPM) up until the point of inserting 
`<AniLink paintDrip to="page-2"> Go to Page 2</AniLink>`

This error is happening:

---
![Bildschirmfoto 2019-12-07 um 17 53 39](https://user-images.githubusercontent.com/49811687/70377967-33144800-191b-11ea-87cf-e4fbfdba9784.png)

----

Changing the preset from paintDrip to Fade or others does not change anything.

**Comment by VeFoWe** [comment]
@TylerBarnes : I've cloned my repository here :

https://github.com/VeFoWe/PropertyOfUndefined

As stated above, it's a basic Gatsby instance that has only the TransitionLink Plugin added.

**Comment by tijsluitse** [comment]
@TylerBarnes thanks for answering. I am busy cloning my repo and making it shareable. Maybe we could look into the repo of @VeFoWe first. Because mine is a bit more complex!

**Comment by TylerBarnes** [comment]
@VeFoWe your error is unrelated and luckily it's a simple fix :)
Your error is `TypeError: Cannot read property 'interestingExitAnimation' of undefined`. And that's because you're referencing `this` from within a functional component which has no `this` context.

You'll have to change this:
```js
const IndexPage = () => (
  <Layout>
    <SEO title="Home" />
    <h1>Test</h1>
    <p>Welcome to your new Gatsby site.</p>
    <p>Now go build something great.</p>
    <div style={{ maxWidth: `300px`, marginBottom: `1.45rem` }}>
      <Image />
    </div>

    <TransitionLink
      to="/page-2"
      exit={{
        trigger: ({ exit, node }) => this.interestingExitAnimation(exit, node),
        length: 1,
      }}
      entry={{
        delay: 0.6,
      }}
    >
      Go to page 2
    </TransitionLink>
  </Layout>
)
```
into something like this
```js
const interestingExitAnimation = (exit, node) => {
  // do some animation here
  console.log(exit, node)
}

const IndexPage = () => (
  <Layout>
    <SEO title="Home" />
    <h1>Test</h1>
    <p>Welcome to your new Gatsby site.</p>
    <p>Now go build something great.</p>
    <div style={{ maxWidth: `300px`, marginBottom: `1.45rem` }}>
      <Image />
    </div>

    <TransitionLink
      to="/page-2"
      exit={{
        trigger: ({ exit, node }) => interestingExitAnimation(exit, node),
        length: 1,
      }}
      entry={{
        delay: 0.6,
      }}
    >
      Go to page 2
    </TransitionLink>
  </Layout>
)
```

**Comment by TylerBarnes** [comment]
@VeFoWe I also switched out your usage of transition link for anilink with paintDrip and it's working for me.

**Comment by TylerBarnes** [comment]
@tijsluitse I just ran into your error when I removed transition link from the gatsby config of a site. Can you double check that it's added to your config?

**Comment by VeFoWe** [comment]
@TylerBarnes : thank you for replying - but that did not solve the issue for me, it did generate the exact same error. 

I've been following these instructions here [https://www.gatsbyjs.org/docs/adding-page-transitions-with-plugin-transition-link/#predefined-transitions](url) step by step - could you please share your repo in which switching  the usage of transition link for anilink with paintDrip is working?

**Comment by TylerBarnes** [comment]
@VeFoWe that was using the repo you provided. I just get a React error from the latest commmit, no transition link specific errors. Have you pushed up your latest work to that repo?

**Comment by TylerBarnes** [comment]
@VeFoWe also there's no usage of anilink in the demo repo you shared but when I add it it works

**Comment by TylerBarnes** [comment]
@VeFoWe I forked your repo and added anilink and deployed to netlify https://musing-morse-b7915e.netlify.com/page-2
https://github.com/TylerBarnes/PropertyOfUndefined
It's working there, but I'm happy to take a look again if you're still running into that error.

FYI The paintdrip animation in that Netlify site is buggy and theres an unrelated fix for that being published on npm right now (1.17.4)

**Comment by tijsluitse** [comment]
Hi @TylerBarnes for me it's still not working. Can I add you as a contributor to my repo?

**Comment by TylerBarnes** [comment]
@tijsluitse thanks for adding me! I can't get the site to run as it requires some env variables. I see you're on v1.16.2 though, try upgrading to 1.17.5 as that may fix the problem for you.

**Comment by tijsluitse** [comment]
@TylerBarnes upgrading does the trick! Thanks 🙏🏻

**Comment by TylerBarnes** [comment]
Woo! Glad to hear it :)

**Comment by hankandre** [comment]
I've been getting this error when attempting to run Jest with `@testing-library/react`. I think the problem is that AniLink/TransitionLink both utilize `gatsby-plugin-transition-link`'s `InternalProvider` and when you try to test the component the Provider isn't an ancestor so the consumer isn't getting the `values` (`disableAnimation`, etc.) it needs.

`InternalProvider` also makes a call to `window.matchMedia` which isn't available in Jest, so it needs to get mocked out as well.

I was able to get the test to pass by doing the following.

```js
import React from 'react';
import { render } from '@testing-library/react';
import InternalProvider from 'gatsby-plugin-transition-link/context/InternalProvider';
import Link from '.';

test('<Link/> component with animation', () => {
    window.matchMedia = jest.fn(() => true);
    const path = '/somewhere'
    const { container } = render(
      <InternalProvider>
          <Link href={href}>Hello</Link>
      </InternalProvider>,
    );
    expect(container.firstChild).toBeInTheDocument();
    expect(container.firstChild).toHaveAttribute('href', path);
}); 
```

If you plan on using this component in your app you probably want to create a wrapper around `@testing-library/react`'s `render` so that you don't have to do this every time you test a component with a `Link` somewhere in its sub-tree..

```js
import React from 'react';
import { render } from '@testing-library/react';
import TransitionLinkProvider from 'gatsby-plugin-transition-link/context/InternalProvider';

export const renderWithTransitionProvider = ui => render(
    <TransitionLinkProvider>
        {ui}
    </TransitionLinkProvider>
);
```
And in your [setupFilesAfterEnv](https://jestjs.io/docs/en/configuration#setupfilesafterenv-array) for Jest mock out `window.matchMedia` (like I did in the test above).

Then you'd use `renderWithTransitionProvider` for your tests where an `AniLink` or `TransitionLink` were present.

**Comment by funkfinger** [comment]
@hankandre thanks for this. Saved me a bit of time!

I took a rather aggressive route and swapped out the `testing-library` `render` with one that always provided the `TransitionProvider` - I have a test setup file that does the following:

```javascript
import {  render as tlRender } from '@testing-library/react';
import TransitionLinkProvider from 'gatsby-plugin-transition-link/context/InternalProvider';
global.render = ui => tlRender(<TransitionLinkProvider>{ui}</TransitionLinkProvider>);
global.window.matchMedia = jest.fn(() => true);
```

**Comment by calsal8** [comment]
I also get this error when rendering TransitionalLink or AniLink from my own Context, which is rendered before the page and `gatsby-focus-wrapper` itself. 

```
<GlobalContext.Provider value={this.state}>
  <div id={'root'} className={`root`}>
    <AniLink to={this.state.backLink} swipe>Back</AniLink>
    {this.props.children}
  </div>
</GlobalContext.Provider>
```

If I wrap AniLink with `<InternalProvider>` it renders without errors, but then I get no transition/animation when I click that link.
I would really appreciate any guidance!

**Comment by ghettosunrise** [comment]
have the same issue 
version 1.18.0

**Comment by Danrrodrigues** [comment]
I had forgotten to add gatsby-cofing.js
plugins: [
`gatsby-plugin-transition-link`,
....

**Comment by balibebas** [comment]
TypeScript users make you're not declaring the component as functonal as [described by Tyler](https://github.com/TylerBarnes/gatsby-plugin-transition-link/issues/161#issuecomment-563471524). In other words you **cannot do this** without hitting the error:

```tsx
import React, { FC } from "react";
import AniLink from "gatsby-plugin-transition-link/AniLink";

const DripLink: FC = ({ children }) => <AniLink paintDrip to="/">{children}</AniLink>
```

Removing `FC` will prevent the error.

**Comment by balibebas** [comment]
TypeScript users make sure you're not declaring the component as functonal as [described by Tyler](https://github.com/TylerBarnes/gatsby-plugin-transition-link/issues/161#issuecomment-563471524). In other words you **cannot do this** without hitting the error:

```tsx
import React, { FC } from "react";
import AniLink from "gatsby-plugin-transition-link/AniLink";

const DripLink: FC = ({ children }) => <AniLink paintDrip to="/">{children}</AniLink>
```

Removing `FC` will prevent the error.

**Comment by twowaydiode** [comment]
I'm having the same issue when using AniLink inside gatsby's wrapRootElement. 
Wrapping with <InternalProvider> or <TransitionLinkProvider> makes the error disappear but animations do not work.

**Comment by animanoir** [comment]
> gatsby-plugin-transition-link

This post has saved me countless times.
