### ISSUE TITLE
Fade out then Fade in, without crossfading?

### ISSUE THREAD

**Issue by MrUltimate** [TylerBarnes/gatsby-plugin-transition-link#173]
I'm trying to create a simple fade between my pages, however, I don't like the default cross-fade behavior of `AniLink's` fade feature. Is there a way I can tweak the fade so that it fades out first, then fades in?

**Comment by TylerBarnes** [comment]
@MrUltimate there's no option for that currently. I would accept a PR adding an entryDelay option if you want to make one. Otherwise you can copy the AniLink fade code and use it as a custom transition link component in your project.
https://github.com/TylerBarnes/gatsby-plugin-transition-link/blob/9052d0b14517e8550582c07574571d8753fb80a1/src/AniLink/Fade.js#L44

**Comment by TylerBarnes** [comment]
Closing this issue for now, but please feel free to PR this in at any time in the future if you're interested.

Thanks again!
