### ISSUE TITLE
Links disabled during transition

### ISSUE THREAD

**Issue by benjam1n** [TylerBarnes/gatsby-plugin-transition-link#187]
Hi there! Is it possible to enable links while transition is happening? Ideally without using portals. This also happens on https://transitionlink.tylerbarnes.ca.

**Comment by TylerBarnes** [comment]
@benjam1n , links are disabled during transitions because there's no way to cancel an animation once it's begun. Clicking one link then clicking another would likely result in unexpected UI bugs for a lot of your users. For example you could click a link that has a slow animation and then spam click a second link that has a faster animation. What would happen in that situation?
I'm open to any ideas on how we can make it work!
