### ISSUE TITLE
How to use with React Spring

### ISSUE THREAD

**Issue by zachgibson** [TylerBarnes/gatsby-plugin-transition-link#34]
First off @TylerBarnes really cool lib you’ve made here! For the life of me I can’t get this to work with React Spring, I think just because I don’t know what’s really happening. Any tips? I’m looking for any simple example of how this would look?

**Comment by TylerBarnes** [comment]
Hey @zachgibson thanks the appreciation!

Check out the react spring folder I just added
https://github.com/TylerBarnes/gatsby-plugin-transition-link/tree/master/example/src/pages/react-spring

And a demo of it working is at https://gatsby-plugin-transition-link.netlify.com/react-spring/a/

Basically if you check out any of the react-spring demos where the state changes on click, that's a good example to look at because it's an animation controlled by a boolean. We can get a true/false out of our transition state / status so any of those examples could easily be modified to use transition link.
http://react-spring.surge.sh/spring#demos

What I did was add just a `to` prop to the Spring component and then depending on wether the page should be mounted or not, i changed the react spring value.

```jsx
const mount = ['entering', 'entered'].includes(transitionStatus)
<Spring
          to={{
            transform: `translateY(${mount ? 0 : '100px'})`,
            opacity: mount ? 1 : 0,
          }}
        >
...
```
mount is true if the page is either entering or has entered.

I think you'll run into one problem which is that react spring isn't duration based. 
There is a way to set a duration in react spring though if you check out http://react-spring.surge.sh/gotchas just above the headline 'Animating "auto"'.

All you need to do is pass in the duration from the entry / exit transition state to the config prop:
```jsx
<Spring ... config={{ duration: 3000 }}>
```

In the example I added I didn't feel the need to connect the duration but now that I'm thinking about it I might as well write out an example.

```jsx
const MySpring = ({ text }) => (
  <TransitionState>
    {({ transitionStatus, exit, entry }) => {
      const mount = ['entering', 'entered'].includes(transitionStatus)
      const duration = mount ? entry.length : exit.length

      return (
        <Spring
          to={{
            transform: `translateY(${mount ? 0 : '100px'})`,
            opacity: mount ? 1 : 0,
          }}
          config={{
            duration: duration,
          }}
        >
          {props => <div style={props}>{text}</div>}
        </Spring>
      )
    }}
  </TransitionState>
)
```
And actually I'll update the example code in the repo too 😂

If the page is on the way in and should be mounted then we use the length from the entry prop, otherwise we take it from exit. 

Let me know if you have anymore questions about this!

**Comment by TylerBarnes** [comment]
Now that I'm thinking about it a bit more, a component could easily be created to just wrap around the Spring component and hook all of this up every time. Then you could easily place that component everywhere that you want to add a react-spring animation.

**Comment by TylerBarnes** [comment]
Oops, I made a mistake in the code above (it's fixed now). Duration in react-spring is in ms but duration in transition link is seconds. You basically need to multiply the time from transitionlink by 1000 to hook up duration properly.

Now that I've played with this a bit I'm considering making a reusable package/component for react-spring that abstracts some of this set up.

**Comment by zachgibson** [comment]
Dude, this is awesome! Thanks for the help, and let me know if I can help with this at all. I’d be glad to.

**Comment by dbismut** [comment]
Hey @zachgibson, the lib looks fantastic but specifying the duration for `Spring` breaks the idea of a spring-based animation, doesn't it?

**Comment by TylerBarnes** [comment]
@dbismut it does but unfortunately there isn't another way to control the timing of the exiting and entering pages mounting and unmounting. I've been thinking of making a little wrapper component around spring which adds a promise to each spring so that each spring has to finish before the page unmounts but that doesn't sound perfect either as pages won't be able to overlap that way.

**Comment by dbismut** [comment]
@TylerBarnes Sorry I mentioned Zach in the first place, my message was meant for you (so again, fantastic lib). I hear you, I'll see if I can get something working when I have some time!

**Comment by TylerBarnes** [comment]
@zachgibson @dbismut this isn't in the docs yet but I actually added a couple things that should make using react spring easier.
 
The above example can now be written like so as of `1.5.1`:

```jsx
const MySpring = ({ text }) => (
  <TransitionState>
    {({ mount, current }) => {
      const ms = current.length * 1000

      return (
        <Spring
          to={{
            transform: `translateY(${mount ? 0 : '100px'})`,
            opacity: mount ? 1 : 0,
          }}
          config={{
            duration: ms,
          }}
        >
          {props => <div style={props}>{text}</div>}
        </Spring>
      )
    }}
  </TransitionState>
)
```

You can also leave off duration if you want and use the natural spring duration but you'll have to work out how long you want your page to stay before unmounting just based on how long the spring happens to be. So you could just enter a time value in enter & exit and tweak it until everything looks good. It's not the most ideal way to do things but I'm confident there will be a better way soon.

**Comment by tompiler** [comment]
For anyone checking this out today - the 

`import { Spring } from 'react-spring'`

from @TylerBarnes excellent example in his post above is now:

`import { Spring } from 'react-spring/renderprops'`

**Comment by alejuu** [comment]
I was able to implement animations with React Spring, but I have a question. There's a component that lives only on the index page; when I navigate from another page to the index I can see the animation, but when I leave the index I can't see anything. I think this happens because this component doesn't exist in the other page. How can I create an exit animation? I don't want to include this component in the other page.

This is the animation:

```
const OpacityTransitionSpring = ({ children, className }) => (
  <TransitionState>
    {({ mount, current, exit }) => {
      const ms = current.length * 1000
      return (
        <Spring
          to={{ 
            opacity: mount ? 1 : 0
          }}
          config={{ 
            duration: ms 
          }}
        >
          {props => <div className={className} style={props}>{children}</div>}
        </Spring>
      )
    }}
  </TransitionState>
)
const TransitionSpringLink= ({ to, className, children }) => (
  <TransitionLink 
    to={to} 
    className={className} 
    exit={{ length: 3 }} 
    entry={{ length: 3 }}
  >
    {children}
  </TransitionLink>
)
```
