### ISSUE TITLE
AniLink cover bg doesn't work with background images

### ISSUE THREAD

**Issue by zzulanas** [TylerBarnes/gatsby-plugin-transition-link#46]
So I'm trying to use the AniLink property with a background png as the `bg` prop, as it says in the docs, but when I use the prop like so:

```
import bg from '../../static/wipebg.png'

<AniLink cover bg={bg} to="/" className="navbar-item" activeStyle = {activeNavStyle}>
              Home
</AniLink>
```

if I can only use CSS that's fine but when looking at the [docs](https://transitionlink.tylerbarnes.ca/docs/anilink/), for cover, it says "This allows you to set a colour or use a background image if you'd like."

In the source it looks like you can set to background, so I'm not sure why it's not working, or maybe I read wrong.

**Comment by TylerBarnes** [comment]
Hey @zzulanas, sorry for the delayed response!
Yes what I mean in the docs is that you can add a background image via css in that field.
Behind the scenes bg just gets added to the background css property. For example: `background: ${props.bg}`.
This way you can also add the background size and positioning since the background property is a shorthand that takes multiple parameters. https://www.w3schools.com/cssref/css3_pr_background.asp

Is there a wording that would make it more clear in the docs to you? I'd like to update it to make it clearer for sure. 

Thanks!

**Comment by zzulanas** [comment]
Awesome thanks, I couldn't get it working with the setup I had but I just ended up using a solid color vs picture. In the docs maybe have like an example of using a picture too instead of just the color?

**Comment by TylerBarnes** [comment]
Finally got a sec to check this out :) Thanks for raising the issue.

I've added an example to the [docs](https://transitionlink.tylerbarnes.ca/docs/anilink/) (near the bottom)

You can see it in action on page two of the [demo site](https://gatsby-plugin-transition-link.netlify.com/page-2) (the second link on the page)

Thanks again

**Comment by paulbcon** [comment]
I am following this thread. Thank you for this plugin. My question is how to access the background image from my src folder in AniLink?

my folder looks like this : src > assets > images > logo.png
 I tried bg="url('../assets/images/logo.png') but I did not see the image on the transition.
