### ISSUE TITLE
Documentation: Suggestions

### ISSUE THREAD

**Issue by LekoArts** [TylerBarnes/gatsby-plugin-transition-link#48]
Hi!

Really appreciate that you built this package. I plan on using it and I'm sure it'll be great once I implemented it. Sadly I have to browse the documentation on Github because the version on the website is just horrible to put it bluntly. With that post I want to point out some things I saw and hope that it can help you improve the documentation.

- The hide/show transition animations while scrolling are irritating and I don't want to wait a couple of seconds after scrolling to see content :( Please remove that completely.

- The docs link on the homepage should also probably link to the installation, not to the third bulletpoint.

- Some parts of your site are not WCAG accessible, e.g. your footer has a color contrast of 1.38 (4.5 would be desirable)

Thanks!

**Comment by TylerBarnes** [comment]
Hey @LekoArts, thanks for the feedback!

- The idea behind the scrolling animation is to remove visual focus from text which isn't currently being read in order to remove visual noise. The animation speed is less than a second but it could be sped up a bit.
- This is a good point about the docs link. The reason it's linking to the third bullet point is so that returning users who want to reference how to use transition link would go there while new users who are starting from the beginning would probably want an overview. The reasoning here is that you're likely installing the plugin far less often than you want to reference how to use it.
- The footer is intentionally partially obscured as my personal site is almost 4 years outdated. I don't think developer documentation for an animation plugin needs to be fully WCAG compliant as I imagine creating web animations would be really hard if you have poor eyesight. I'm definitely open to changing this as I could easily be wrong about that. 

With that being said, you're welcome to open a PR on the documentation repo at https://github.com/TylerBarnes/TransitionLinkDocs. I've been super busy lately and it was a huge effort to create this plugin and docs site in my free time. I do have plans to improve the docs and write some more tutorials as I do bug fixes and enhancements but it is hard sometimes to find the time to get it done sooner than later.

Thanks again!

**Comment by TylerBarnes** [comment]
I should add that my bullet points aren't to refute your criticisms or anything like that, just to explain the reason behind why I chose to do things like that when I made the docs. I'm not a practising designer and I'm open to collaboration on this for sure.

**Comment by LekoArts** [comment]
Thanks for the reply!

- With having this explanation in mind I still can't understand the reasoning. If I scroll the text fades in, but when I actually read something I can see everything. The way you describe it it should be the other way around. I also can't scroll the page quickly and scan it for the headlines because all text is hidden. I'm not the only person who does that :D
- Yeah makes sense!
- The footer was just one example, I also found some other texts that were difficult to read (even for me who hasn't got a disability). So I think this is a easy improvement

**Comment by TylerBarnes** [comment]
I can definitely see what you're saying and it makes sense to me.
If you have time to make the changes that would be really awesome.

Thanks @LekoArts ! I appreciate the feedback and help

**Comment by TylerBarnes** [comment]
Fixed in https://github.com/TylerBarnes/TransitionLinkDocs/pull/3
Thanks for the good suggestions @LekoArts !
