### ISSUE TITLE
Use with react-pose?

### ISSUE THREAD

**Issue by Polcius** [TylerBarnes/gatsby-plugin-transition-link#5]
What would be the way to use it with react-pose? Is it absolutely necessary to include gsap? 

Btw, congrats on the plugin!

**Comment by TylerBarnes** [comment]
Hey @Polcius , thanks!

Because I've added state based transitions, GSAP isn't necessary.

[I created an example for you](https://gatsby-plugin-transition-link.netlify.com/react-pose/pose-1), Click the box to see a very simple fade transition.

[Check the code](https://github.com/TylerBarnes/gatsby-plugin-transition-link/blob/master/example/src/components/Poses/ExamplePose.js) and the [state transitions section](https://github.com/TylerBarnes/gatsby-plugin-transition-link#state-transitions) in the readme for more.

**Comment by TylerBarnes** [comment]
You might want to look at the [pages](https://github.com/TylerBarnes/gatsby-plugin-transition-link/tree/master/example/src/pages/react-pose) as well
