### ISSUE TITLE
Blink  / Flash / Reload After clicking (AniLink)

### ISSUE THREAD

**Issue by joebentaylor** [TylerBarnes/gatsby-plugin-transition-link#80]
Hi, so real simple issue you.

Regardless of what Anilink transition i use, when clicking a link the transition plays, but its like at the end of the transition the content reloads / page reloads, it gives a flash / blink effect and i have no clue as to why or how to fix it.

Test it out here:
[Click here](https://mortgagesremortgages.netlify.com)

Im not duplicating the layout either.

**Comment by TylerBarnes** [comment]
I've seen this before, it was because font files were being reloaded on every page load. If you open the network tab of chrome dev tools and look at the requests tab you'll see your font files get reloaded after navigating. I'm not really sure why this happens but I'm guessing you're using emotion or styled-components and adding your fonts with `injectGlobal()`. Last time I "solved" this I just moved those `@font-face` declarations into a separate css file and imported that css file.

**Comment by joebentaylor** [comment]
Hmm this is very interesting. Im not sure what to do in this case. Im using styled components, youre correct!

So what are you suggesting to do? Put these in a standard .css file and import them into the layout files root? @TylerBarnes

**Comment by TylerBarnes** [comment]
Yes, exactly, if you put your font imports into a .css file it should fix the issue. 
I have a feeling this is because in a normal gatsby site the props on pages typically don't change after the page loads - so they don't re-render. In our case, the page props change as the transition goes through different statuses. I think it might actually be a bug in the styled components plugin or Gatsby potentially though I'm not totally sure. I've been thinking of removing the transition statuses from page props and having people only access them via `<TransitionState />`.

**Comment by joebentaylor** [comment]
Ill give this a go soon and let you know the outcome 👍
