### ISSUE TITLE
Back functionality broken

### ISSUE THREAD

**Issue by joebentaylor** [TylerBarnes/gatsby-plugin-transition-link#89]
Hey! After clicking through to a page from a link, if i press the native back buttons. the page flashes clear and stays like that with no content inside. I think ive seen this problem before listed on here, but couldnt find it.

**Comment by joebentaylor** [comment]
This only happens on Mobile

**Comment by TylerBarnes** [comment]
There was another issue that was opened recently that made me think the timing of when it prevents the back button from being pressed is off slightly. Are you able to provide a repo I can use to debug?

**Comment by JPrisk** [comment]
+1 i've noticed this issue as well, super strange. Can't seem to find an fault in the css being applied

**Comment by JPrisk** [comment]
I thought that there was some issue with the handling of elements when the user navigated back using the native functionality. Turns out because I was using the transationStatus as a className to manage animations when the user clicked back and 'POP' is the default status rather than 'entered' by css was not being triggered. Simple fix

**Comment by Simon-Tang** [comment]
Could we add a section in the documentation for possible values of `transitionStatus`? I think there are probably plenty of sites that would be checking for `"entered"` and not handling the `"POP"` case. (In fact, I suspect https://transitionlink.tylerbarnes.ca/docs/transitionlink/ has this issue, too).

Perhaps we could have a built-in option to handle [`onpopstate`](https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onpopstate) by triggering the usual page transitions? (In this case, would it be easy to also trigger the page transitions on page load?).

**Comment by joebentaylor1995** [comment]
Sorry for such a late reply, I'm not sure if I'm still getting the same error anymore... Ill test and share the Repo if i am, can you message me directly @TylerBarnes

**Comment by gmossong** [comment]
@TylerBarnes @joebentaylor1995 I've added [a repo](https://github.com/gmossong/transition-link-demo) which demonstrates this issue. I also set it up [on Netlify](https://thirsty-liskov-726f68.netlify.com). To reproduce, load up the Netlify site then click through each page in the top menu; **About, Projects** and **Contact**. Then once you have made it to Contact hit your browsers back button.

Notice how when you click back, once you get to the Home page it works, but the other pages don't.

The demo uses gatsby-image for the images. React-pose for the animations.

**Comment by joebentaylor1995** [comment]
I resolved this issue, with it being related to what @JPrisk had mentioded, it was a case of adding some arguments to say if something had a specific class toggle a different animation, so you have to be careful with what animations you use based on the classes applied

**Comment by TylerBarnes** [comment]
Hey! Apologies for taking so long to get to this. A fix is published in `gatsby-plugin-transition-link@1.17.7`

Turns out this was related to some code where I was trying to get reversed animations working when going backwards in the browser. Since that feature never made it, I've simply removed all the related code and it's now returning the expected status instead of POP.
